### ISSUE TITLE
Can't compile. Instructions literally do not work.

### ISSUE THREAD

**Issue by Acumenium** [pokemon-speedrunning/gambatte-speedrun#101]
README.md doesn't matter since not only do its contents not work, its predecessor, INSTALL.md doesn't complete. There's usually some error about "invalid crypto engines", it not being able to find "python2" ($ pacman -S perl ruby python2 mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain), or any other number of errors of it not actually downloading or installing anything.

README.md mentioned being able to compile the core here for use in other emulators, I assume RetroArch or BizHawk. I wanted to do that since it's obviously a more up-to-date core than the ones featured in those emulators, but I can't.

**Comment by CasualPokePlayer** [comment]
"invalid crypto engines" means your build environment is fucked somehow. Not a problem on our side.

Also no, this emulator cannot be compiled for use in Retroarch or BizHawk. Those emulators require specific features to interface with their respective APIs, which we do not have. Don't even know where you even got the idea that this can just compile and run in other frontends.

Also, the BizHawk core is more up to date than us at the moment, so you're wrong on that front.

**Comment by Acumenium** [comment]
I highly doubt I'm the first person to have had an issue with the ten page INSTALL.md.

If it can't be compiled for use in those environments, why on earth is there a part of it that mentions compiling for use with TASing and botting?

It definitely isn't, since BizHawk's Gambatte core doesn't support a lot of the RNG functions that this one does.

**Comment by CasualPokePlayer** [comment]
The shlib cannot be used currently with BizHawk, rather the PSR community has its own tools for "TASing and botting" which use the shlib. BizHawk is not the only way to TAS/bot (and would be rather slow for botting).

Also, what "rng functions" are you talking about? The emulation core is more accurate on BizHawk at the moment, RNG in games should be identical or maybe more accurate in BizHawk in any case.

**Comment by Acumenium** [comment]
A lot. Notably BizHawk's Gambatte core has absolutely no support for console-accurate DSUM manipulation, like the one used to get the near-perfect Lv6 Nidoran-M in Pokemon Yellow. https://www.youtube.com/watch?v=B40BsgzoGVw

Gambatte-PSR does, but it's such a clunky emulator to use. Input recording is too valuable because it lets you then record the actual video at a later point instead of needing this gigantic block of time to play at all once.

**Comment by TiKevin83** [comment]
Bizhawk's gambatte core has the same console accuracy as GSR, you just need to use the agb variant of the cgb bios by selecting console mode GBA

**Comment by Acumenium** [comment]
Gambatte-Speedrun is using the GBA version of the GBC bios? I had no idea...

Thanks!
