### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by Shad0wKaz** [pokemon-speedrunning/gambatte-speedrun#3]
How would I get this on Mac.  I love running Pokemon Red but recently have found myself not able to compete with the OpenEmu version of Gambatte due to the Select+Up+B Nido Manip strat not working on that emulator (don't ask why, it just doesn't).

**Comment by entrpntr** [comment]
Here are some tentative Gambatte-speedrun r668 macOS binaries (equivalent to r664 for Windows). These should theoretically work for macOS Sierra (version 10.12) and higher. If these appear to work without issue, there should be an official release through github at some point:

- PSR version: https://drive.google.com/file/d/1FhtrIMB1AgS2uVGU46UzdhIo1tQDGLda/view?usp=sharing
- non-PSR version: https://drive.google.com/file/d/1OIN60zGSDG4MsdarJV51wI8LQWYeOOnd/view?usp=sharing

**Comment by entrpntr** [comment]
As of r717, releases now comes with macOS builds: https://github.com/pokemon-speedrunning/gambatte-speedrun/releases/tag/r717. As of now, there's support for macOS 10.13 and newer.
