### ISSUE TITLE
Tiny Toon Adventures - Babs Big Break has graphical issues in GBC mode.

### ISSUE THREAD

**Issue by EZGames69** [pokemon-speedrunning/gambatte-speedrun#41]
While TASing this game in BizHawk, I noticed any time the screen transitions, there is junk on the screen like this:

![Tiny Toon Adventures - Babs' Big Break (USA, Europe) 2020-05-29 16 51 18](https://user-images.githubusercontent.com/44628443/83306799-410f9b00-a1d1-11ea-8c60-bc554de50da5.png)

I tested this in the latest upstream for GSR and the issue is there as well.  I also tested this with BizHawk's GBHawk and this doesnt happen in its GBC mode.

and keep in mind, this only affects GBC mode, it is not present in GB mode.

**Comment by entrpntr** [comment]
Thanks for the detailed information. This visual glitching doesn't appear in r664, so I'm going to assume we missed something in #27 that is causing this. 

This cart also has a title that runs into the CGB flag at $0143, something we probably don't detect properly. Will have to revisit our fix for this, but these should be good leads.
