### ISSUE TITLE
"Close ROM" has no effect during reset fadeout/stall

### ISSUE THREAD

**Issue by CasualPokePlayer** [pokemon-speedrunning/gambatte-speedrun#71]

**Comment by entrpntr** [comment]
This was intentionally added to make it more difficult for runners to (either accidentally or intentionally) bypass the reset fade on GBP. 

Bypassing the fade is against the rules anyway, but there didn't seem to be a real downside to outright preventing closing ROMs mid-reset. Is there a compelling reason to support it?

**Comment by CasualPokePlayer** [comment]
Really, probably would be better to just gray out the option then rather it would just "do nothing" (which hearing that explanation, it's not really a bug but it has the appearance of a bug due to its implementation).
